DROP TABLE IF EXISTS vitals;
DROP TABLE IF EXISTS diagnosis;
DROP TABLE IF EXISTS bill;
DROP TABLE IF EXISTS visitation;
DROP TABLE IF EXISTS patients;
DROP TABLE IF EXISTS staff;
DROP VIEW IF EXISTS _queue;